### ISSUE TITLE
Django test handling

### ISSUE THREAD

**Issue by djsmith42** [carljm/django-transaction-hooks#21]
Since Django tests start a new transaction and never commit it, any `on_commit` hooks will never get a chance to run in test mode. We've worked around this by writing a test utility that simply calls all registered `on_commit` hooks, but sometimes this isn't enough.

What do you think about the idea of running `on_commit` hooks when a `SAVEPOINT` is committed, but only if we are in test mode? I know there are probably some false positives, but it would simplify testing quite a bit for us.

I'd love to discuss this idea more.

**Comment by carljm** [comment]
Thanks for the thoughtful report.

I'm pretty hesitant to introduce any changes to the production code that are test-aware. In general, Django doesn't even really have a concept of "test mode" that you can hook into to check whether tests are currently being run, and I think that's a good thing -- the tests should be responsible for setting up the conditions for their success, it shouldn't be the responsibility of production code to be testing-aware.

And specifically the idea of running hooks on savepoint commit is unsafe, I think. Some savepoints might be "would have been a transaction commit if we weren't within a test transaction," but not all. Some savepoints would always have been savepoints, because they're nested in another transaction even under production usage. In these cases your proposal would result in a significant change in code semantics when under test, which is not good.

The documentation already discusses this issue, and suggests using `TransactionTestCase` if you need to test the results of an `on_commit` hook. Since you need to use `TransactionTestCase` to test any other transaction behavior in Django, and `on_commit` is "transaction behavior," this seemed like a reasonable limitation to me, and so far in my projects it's been adequate.

If that's not adequate, I'd be inclined to go the same direction you did, and write a utility you can call from a test which runs any pending `on_commit` hooks; this shouldn't be too difficult to write.

Since transaction-hooks has been merged into Django 1.9, I don't really want to add any more features to it, but we could see how the other Django core devs feel about adding a utility like that to Django 1.10. I don't have strong feelings either way about it.

**Comment by djsmith42** [comment]
Oh, I didn't realize it was in 1.9. I'll keep an eye on that and see if there's anything we can do to alleviate some of our testing pain.

**Comment by carljm** [comment]
Ok. Closing this issue for now, then.
